<a href="https://www.kaggle.com/code/hugogrou/projeto-cdg?scriptVersionId=299521268" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Inspeção Inicial do Dataset

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/madhu41289/avazu-ctr-prediction-exp/sampleSubmission/sampleSubmission.csv
/kaggle/input/datasets/madhu41289/avazu-ctr-prediction-exp/test/test.csv
/kaggle/input/datasets/madhu41289/avazu-ctr-prediction-exp/train/train.csv

Bernardo Fernandes

In [2]:
import pandas as pd
import numpy as np
from IPython.display import display

file_path = "/kaggle/input/datasets/madhu41289/avazu-ctr-prediction-exp/train/train.csv"
chunk_size = 1_000_000

total_rows = 0
null_counts = None
duplicate_count = 0
columns = None
dtypes = None

seen_hashes = set()
sample_data = []

print("A processar dataset em blocos...")

for i, chunk in enumerate(pd.read_csv(file_path, chunksize=chunk_size)):
    
    total_rows += len(chunk)
    
    # Mostrar progresso de forma limpa (sem spam)
    if (i + 1) % 5 == 0:
        print(f"{(i+1)} milhões de linhas processadas...")
    
    # Guardar primeiras 5 linhas
    if i == 0:
        first_rows = chunk.head()
        columns = chunk.columns.tolist()
        dtypes = chunk.dtypes
    
    # Guardar amostra até 2M linhas
    if len(sample_data) < 2:
        sample_data.append(chunk)
    
    # Valores nulos
    if null_counts is None:
        null_counts = chunk.isnull().sum()
    else:
        null_counts += chunk.isnull().sum()
    
    # Duplicados reais entre blocos
    row_hashes = pd.util.hash_pandas_object(chunk, index=False)
    for h in row_hashes:
        if h in seen_hashes:
            duplicate_count += 1
        else:
            seen_hashes.add(h)

# Criar dataframe de amostra
df_sample = pd.concat(sample_data, ignore_index=True)

print(" RESULTADOS GERAIS ")

# PRIMEIRAS 5 LINHAS 

print(" PRIMEIRAS 5 LINHAS ")

display (first_rows)

# DIMENSÃO
print("Dimensão do dataset (linhas, colunas):", (total_rows, len(columns)))

print("Número de variáveis:", len(columns))

print("Lista das variáveis:")
display(pd.DataFrame(columns, columns=["Variáveis"]))

print("\nTipos de dados:")
display(dtypes.to_frame(name="Tipo de Dado"))

print("\nValores nulos por coluna:")
display(null_counts.to_frame(name="Valores Nulos"))

print("Total de valores nulos:", int(null_counts.sum()))

print("Número total de duplicados reais:", duplicate_count)



# ESTATÍSTICAS NUMÉRICAS


print(" ESTATÍSTICAS NUMÉRICAS ")

numeric_cols = df_sample.select_dtypes(include=["int64", "float64"])

if len(numeric_cols.columns) > 0:
    display(numeric_cols.describe(percentiles=[0.25, 0.5, 0.75]))
else:
    print("Não existem variáveis numéricas.")



# ESTATÍSTICAS CATEGÓRICAS


print(" ESTATÍSTICAS CATEGÓRICAS ")

categorical_cols = df_sample.select_dtypes(include=["object"])

if len(categorical_cols.columns) > 0:
    display(categorical_cols.describe())
else:
    print("Não existem variáveis categóricas.")

A processar dataset em blocos...
5 milhões de linhas processadas...
10 milhões de linhas processadas...
15 milhões de linhas processadas...
20 milhões de linhas processadas...
25 milhões de linhas processadas...
30 milhões de linhas processadas...
35 milhões de linhas processadas...
40 milhões de linhas processadas...
 RESULTADOS GERAIS
 PRIMEIRAS 5 LINHAS

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1.000009e+18,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,1.000017e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,1.000037e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,1.000064e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,1.000068e+19,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157

Dimensão do dataset (linhas, colunas): (40428967, 24)
Número de variáveis: 24
Lista das variáveis:

           Variáveis
0                 id
1              click
2               hour
3                 C1
4         banner_pos
5            site_id
6        site_domain
7      site_category
8             app_id
9         app_domain
10      app_category
11         device_id
12         device_ip
13      device_model
14       device_type
15  device_conn_type
16               C14
17               C15
18               C16
19               C17
20               C18
21               C19
22               C20
23               C21

Tipos de dados:

                 Tipo de Dado
id                    float64
click                   int64
hour                    int64
C1                      int64
banner_pos              int64
site_id                object
site_domain            object
site_category          object
app_id                 object
app_domain             object
app_category           object
device_id              object
device_ip              object
device_model           object
device_type             int64
device_conn_type        int64
C14                     int64
C15                     int64
C16                     int64
C17                     int64
C18                     int64
C19                     int64
C20                     int64
C21                     int64

Valores nulos por coluna:

                  Valores Nulos
id                            0
click                         0
hour                          0
C1                            0
banner_pos                    0
site_id                       0
site_domain                   0
site_category                 0
app_id                        0
app_domain                    0
app_category                  0
device_id                     0
device_ip                     0
device_model                  0
device_type                   0
device_conn_type              0
C14                           0
C15                           0
C16                           0
C17                           0
C18                           0
C19                           0
C20                           0
C21                           0

Total de valores nulos: 0
Número total de duplicados reais: 0
 ESTATÍSTICAS NUMÉRICAS

,id,click,hour,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
count,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06
mean,9.337745e+18,1.616045e-01,1.410210e+07,1.005012e+03,2.511090e-01,1.006004e+00,2.346770e-01,1.842631e+04,3.185641e+02,5.700759e+01,2.062724e+03,1.577069e+00,1.905398e+02,4.530001e+04,6.807638e+01
std,5.378170e+18,3.680877e-01,2.573399e+00,1.030733e+00,4.668109e-01,4.172392e-01,6.933022e-01,3.767175e+03,1.972680e+01,3.869259e+01,4.752705e+02,1.353921e+00,2.870427e+02,4.982698e+04,4.136320e+01
min,9.984920e+12,0.000000e+00,1.410210e+07,1.001000e+03,0.000000e+00,0.000000e+00,0.000000e+00,3.750000e+02,1.200000e+02,2.000000e+01,1.120000e+02,0.000000e+00,3.300000e+01,-1.000000e+00,1.300000e+01
25%,4.555174e+18,0.000000e+00,1.410210e+07,1.005000e+03,0.000000e+00,1.000000e+00,0.000000e+00,1.570800e+04,3.200000e+02,5.000000e+01,1.722000e+03,0.000000e+00,3.500000e+01,-1.000000e+00,4.300000e+01
50%,9.531133e+18,0.000000e+00,1.410210e+07,1.005000e+03,0.000000e+00,1.000000e+00,0.000000e+00,1.949300e+04,3.200000e+02,5.000000e+01,2.201000e+03,2.000000e+00,3.900000e+01,-1.000000e+00,6.100000e+01
75%,1.401388e+19,0.000000e+00,1.410211e+07,1.005000e+03,0.000000e+00,1.000000e+00,0.000000e+00,2.161100e+04,3.200000e+02,5.000000e+01,2.480000e+03,3.000000e+00,1.750000e+02,1.000840e+05,7.900000e+01
max,1.844673e+19,1.000000e+00,1.410211e+07,1.012000e+03,7.000000e+00,5.000000e+00,5.000000e+00,2.176300e+04,1.024000e+03,1.024000e+03,2.505000e+03,3.000000e+00,1.835000e+03,1.002480e+05,2.210000e+02

 ESTATÍSTICAS CATEGÓRICAS

,site_id,site_domain,site_category,app_id,app_domain,app_category,device_id,device_ip,device_model
count,2000000,2000000,2000000,2000000,2000000,2000000,2000000,2000000,2000000
unique,2473,2653,22,3108,206,27,163262,557935,5253
top,85f751fd,c4e18dd6,50e219e0,ecad2386,7801e8d9,07d7df22,a99f214a,6b9769f2,8a4875bd
freq,695705,725669,759388,1304295,1369155,1326611,1665877,10609,115104

Bernardo Fernandes